# action.yml
name: 'Swiftlint'
description: 'Runs swiftlint script'
inputs:
  version:
    description: 'Swiftlint version'
    required: true
    default: ''
# runs:
#   using: 'docker'
#   image: 'Dockerfile'
#   args:
#     - ${{ inputs.version }}

runs:
  using: "composite"
  steps:
    - name: Lint
      run: |
        URL="https://github.com/realm/SwiftLint/releases/download/${{ inputs.version }}/swiftlint_linux.zip"
        echo "$URL"
        curl -LO "$URL"
        unzip swiftlint_linux -d ${{ github.action_path }}/swiftlint
        rm -rf swiftlint_linux.zip
        ls
        echo "$(pwd)"
        ls ${{ github.action_path }}/swiftlint
        ${{ github.action_path }}/swiftlint/swiftlint version
        ${{ github.action_path }}/swiftlint/swiftlint lint --reporter github-actions-logging
      shell: bash